# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d2b417420397c5a951f710aec6e273534913d0c1ce0a37ff1cf6c5d6c61038ac09ba1f9e5a4491bba246f521ac161aac6389b56e661e2785eb6b13bcd85de3

test:
  secret_key_base: 6c6617e96784c5f9ace74857f35cb6fd918a1ee46080b883fdc93b266e610be5298c8392a5c34a443d9f25daf5d4e1bc1b1756a0dbe6f05efedd2590528cd8bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
